const Home = () => {
    return (

        <section>
            <div className="bg-[red] mt-[8rem]">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Tenetur tempora illo, exercitationem rerum sunt recusandae enim vel suscipit libero, est ipsa necessitatibus soluta officiis explicabo ipsam consequatur at error similique ad. Sequi aut voluptatem labore doloribus ducimus magnam dignissimos quas porro excepturi odit praesentium placeat explicabo sunt a molestiae ipsum maiores doloremque perspiciatis iusto, recusandae accusantium eum. Vel harum eaque nam commodi nulla eveniet ipsum saepe ipsa numquam reiciendis, ab facilis ducimus qui necessitatibus similique minus placeat earum ullam odio facere eius aspernatur labore hic. Nesciunt expedita ullam earum laborum porro voluptates odit similique quia veniam cum perferendis itaque optio facilis reiciendis magni, libero quam nemo, assumenda id! Ad, temporibus? Pariatur culpa quia nisi sequi deleniti doloremque, debitis est labore magnam maiores commodi odit exercitationem maxime earum qui accusamus, soluta quod quas neque quos perferendis provident eum autem voluptas? Eaque officia ut esse rem dicta accusamus et. Iure facere necessitatibus nulla eligendi pariatur a doloremque ipsa cupiditate molestiae dicta, eaque nisi animi dolorum sint ratione dolor recusandae dolores et facilis! Officia dignissimos qui ipsum nulla aut quos numquam? Dicta dolore quae maiores veniam vero! Aperiam expedita, debitis minima, voluptatum accusantium tenetur corporis eaque, consequatur esse id vel provident eveniet aspernatur nostrum tempora possimus. Iusto veritatis totam incidunt corporis quasi in sequi labore, reprehenderit magnam quidem vel temporibus necessitatibus itaque blanditiis eveniet dolor laudantium, ducimus quis quos nihil veniam, dolorum ab. Harum, nesciunt quasi rerum officia delectus sunt molestias dolores dolor at, dolorum, quam quas aliquam. Sequi iusto cumque repellat. Eligendi unde doloremque neque consequatur, dolorum eos nihil in quasi ab aliquid at. Laboriosam voluptate, id ipsa corrupti fugit esse maxime at, soluta quisquam sint tempora! Libero labore cupiditate fugit blanditiis molestiae sint? Odio fugiat rerum velit quod quisquam ea, qui, quibusdam omnis corrupti ullam voluptatum laudantium labore laboriosam dolorum eos, minima dicta deserunt autem. Id veritatis, recusandae amet exercitationem quas voluptate qui hic illo deleniti enim eligendi, esse, itaque eum. Nobis adipisci voluptas, labore dolorem facere eum eos sit fugiat officiis ipsum libero ullam aliquid beatae iusto saepe mollitia fugit. Saepe, id tempora neque sapiente officia ea inventore tenetur soluta hic! Corrupti tempora magni facilis unde. Labore, vero eum suscipit maiores quasi eaque similique sed aperiam? Magni, tenetur? Ut quod quidem officia perspiciatis eaque? Quibusdam facere harum ea odit qui deserunt voluptate, error corrupti inventore dignissimos ex ipsum officiis animi id doloribus sit temporibus? Molestias ea nostrum quam necessitatibus culpa.
            </div>
        </section>
    )
}

export default Home